### ISSUE TITLE
DGML editor prerequisite

### ISSUE THREAD

**Issue by cocowalla** [marss19/reference-conflicts-analyzer#10]
Just had the same problem as in #7, and would like to make a couple of suggestions:

1. Would be good to mention the prerequisite DGML editor in the [extension overview](https://marketplace.visualstudio.com/items?itemName=MykolaTarasyuk.ReferenceConflictsAnalyser#overview)
2. Ideally the extension could detect the presence of the DGML editor, and show a message if it's not installed

When it didn't work OOTB, I was pretty close to just uninstalling this and forgetting about it, so it would be good to point others in the right direction 👍

**Comment by marss19** [comment]
Thanks for the suggestions.
