### ISSUE TITLE
Support for missing publickeytoken

### ISSUE THREAD

**Issue by tds9051** [marss19/reference-conflicts-analyzer#11]
The code fails when a publickeytoken is not present in the assembly redirect.

Fix on line 84 of ConfigurationHelper.cs
         PublicKeyToken = assemblyIdentityElem.Attributes["publicKeyToken"]?.Value,

**Comment by marss19** [comment]
Thanks for the suggestion, I fixed the issue.

**Comment by tds9051** [comment]
Dear,

Thank you for the changes.

Ing. Tony Daems
Technical Director
IALA Industrial Member

[logo_300]

ALSIC bvba
Derbystraat 25
9051 Sint-Denijs-Westrem
Tel : +32-9-265.91.14
GSM: +32-473-80.73.24
tony.daems@alsic.be<mailto:tony.daems@alsic.be>
