### ISSUE TITLE
Tool is showing plain XML 

### ISSUE THREAD

**Issue by MatteoMeil** [marss19/reference-conflicts-analyzer#7]
In VS2017 I made a fresh installation of the tool and when I try to use it with a dll made by me, the output is a plain XML code.
It's just a bug or I'm missing something?

**Comment by marss19** [comment]
Hi,

In VS2017 you need to have the DGML editor installed. It is in the VS installer -> Modify, under "Individual Components" -> "Code Tools"

Regards,
Mykola





08 січня 2018, 17:10:13, від MatteoMeil <notifications@github.com>: 


In VS2017 I made a fresh installation of the tool and when I try to use it with a dll made by me, the output is a plain XML code.
It's just a bug or I'm missing something?
